# -*- coding: utf-8 -*-
"""Webhacking.kr_old-06.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19egGiCLL3bakb0TFGMlESMn86NLPOpmE
"""

import base64

def reverse_replace(s):
    s = s.replace("1", "!")
    s = s.replace("2", "@")
    s = s.replace("3", "$")
    s = s.replace("4", "^")
    s = s.replace("5", "&")
    s = s.replace("6", "*")
    s = s.replace("7", "(")
    s = s.replace("8", ")")
    return s

id = 'admin'.encode()
pw = 'nimda'.encode()

for j in range(20):
    pw = base64.b64encode(pw)
    id = base64.b64encode(id)

id = reverse_replace(id.decode())
pw = reverse_replace(pw.decode())

print(id)
print('\n\n')
print(pw)

import base64

# 문자 치환을 역으로 수행하는 함수 정의
def reverse_replace(s):
    s = s.replace("1", "!")
    s = s.replace("2", "@")
    s = s.replace("3", "$")
    s = s.replace("4", "^")
    s = s.replace("5", "&")
    s = s.replace("6", "*")
    s = s.replace("7", "(")
    s = s.replace("8", ")")
    return s

# 관리자 아이디와 비밀번호를 UTF-8 인코딩하여 바이트로 변환
id = 'admin'.encode()
pw = 'nimda'.encode()

# 각각 20번의 base64 인코딩 적용
for j in range(20):
    pw = base64.b64encode(pw)
    id = base64.b64encode(id)

# 문자 치환을 역으로 수행하여 원래의 값 도출
id = reverse_replace(id.decode())
pw = reverse_replace(pw.decode())

# 결과 출력
print("Decoded ID:", id)
print("\n\n")
print("Decoded Password:", pw)