# -*- coding: utf-8 -*-
"""XOR_Decode.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QAxX1i8AJpy6EtWcDYr6cZCf_SgBrzTo
"""

hex_value = "54586b6458754f7b215c7c75424f21634f744275517d6d"
decoded_hex = bytes.fromhex(hex_value)

possible_messages = []
for key in range(256):
    decoded_message = bytes([byte ^ key for byte in decoded_hex])
    possible_messages.append(decoded_message)

for message in possible_messages:
    print(message.decode("utf-8", errors="ignore"))